### ISSUE TITLE
Bug: S2 Neither client nor professional can leave review via post-service email

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#111]
Site: live

The same behavior happens regardless of whether the _client_ or _professional_ is logged in or out.

To reproduce:
1. As a client, book and complete a service session. (I used a free consultation)
2. When you receive a post-service email, click on the link in the email to review the service professional (As a professional, click the link to review the client).
3. You will initially navigate to `https://loconomics.com/reviews/[id]`, but then the page will immediately bounce to the home page `https://loconomics.com/reviews/[id]#!/home` and you will see the following error dialog.

![no-review](https://cloud.githubusercontent.com/assets/6644016/21859236/ba3ca05e-d7e0-11e6-8cd7-976d2bde3c45.jpg)

**Comment by joshdanielson** [comment]
@IagoSRL I did this SQL script to both dev and live databases as a workaround for now:
`UPDATE positions
SET SendReviewReminderToClient = 0`

I "think" this should send the communications after services being completed that do not include the request to review services. We'll revise this table when we complete reviews. I did a test but had a payment exception error and had to manually complete the booking in the db so not sure how to test. 

Can you let me know if this sounds right?

**Comment by IagoSRL** [comment]
Sounds right. You may try a free booking for testing (like a consultation).

Please, try to found error message, steps to reproduce, about the payment error and open an issue for that.

**Comment by IagoSRL** [comment]
I was checking the messaging code, and the flag for reviews seems being respected when preventing to send the 'review reminder' emails, and inside some 'BookingCompleteHIPAA' templates, but is not respected at other ones likes:
- \web\en-US\EmailCommunications\Booking\BookNow\ToClient\BookingCompleted.cshtml
- \web\en-US\EmailCommunications\Booking\Marketplace\ToClient\BookingCompleted.cshtml
- \web\en-US\EmailCommunications\Booking\Marketplace\ToServiceProfessional\BookingCompleted.cshtml
- \web\en-US\EmailCommunications\Booking\ServiceProfessionalBooking\ToClient\BookingCompleted.cshtml

@joshdanielson I suppose the language and `if else` to apply could be similar to the HIPAA version, right?

**Comment by IagoSRL** [comment]
Also @joshdanielson please check this comment I set and following lines because something is being done wrong here (we can comment in a few minutes): https://github.com/loconomics/loconomics/blob/is111-review-reminders/web/App_Code/LcMessaging.cs#L807

**Comment by IagoSRL** [comment]
I pushed changes here to *dev* site for testing. Please @joshdanielson review when you can, using /tests/TestMessaging or /tests/TestEmails should help.

Anyway, I will open an issue to review and document clearly what info and options should go on every booking communication, since some details I saw may not be completely correct and if translations would happen soon I think is important to keep correct and clear.

**Comment by joshdanielson** [comment]
@IagoSRL let's chat about this on our call tomorrow morning as I tested the communications and am still getting the request to review. I think it just needs a switch statement or I'll just remove the language for now.

**Comment by IagoSRL** [comment]
There is yet another flag for service professionals that we forget, `SuppressReviewOfClient`, and need to be checked to choose to display/hide the review button and language, just like we did with `SendReviewReminderToClient` in client targeted emails.
