### ISSUE TITLE
Bug S2 Unable to save notes on bookings without a location

### ISSUE THREAD

**Issue by situatedbit** [loconomics/loconomics#119]
Site: live

As a professional, I wanted to modify the notes in a completed booking (https://loconomics.com/#!appointment/2017-01-12T17:00:00.000Z/7102096). The booking is a phone consultation so it does not have a service location or area. When I try to save notes on the booking card in the calendar view, the page locks while saving changes. 

Steps to reproduce
1. as a professional, view a completed booking (or any booking, maybe) that does not have a service location, like a phone consultation
2. click the _Edit_ button to add notes
3. Add notes to self
4. On the booking card, click the _Save_ button
5. The button label will become _Saving changes_, but it will not actually save any changes. It will be stuck in this state. 

When I refresh the page, the notes have not been saved.

Here's a screenshot of the call stack:
![01-callstack](https://cloud.githubusercontent.com/assets/6644016/21904739/8a564cb2-d8b9-11e6-9c62-1e12271f7dae.png)

**Comment by IagoSRL** [comment]
As commented at #60, I found this bug and other close related when testing the fix there, and I fixed that several bugs. The error message and stack is exactly what I had, and too the steps to reproduce.

Changes were implemented at the branch *is60* and at *dev* right now, please @situatedbit to double check, test it and confirm is fixed or provide new details. Thanks

**Comment by situatedbit** [comment]
@IagoSRL 

This is still not working correctly on dev. 

I tested two scenarios, both with over-the-phone service bookings.

In the first case, I tried adding notes to the booking before the booking occurred, and in the second, I tried modifying the booking after it occurred. In both cases, I received the same error message:

![saving-booking](https://cloud.githubusercontent.com/assets/6644016/22383583/41f0e776-e47f-11e6-8886-c7a312108ca1.jpg)

Here are the PUT params for http://dev.loconomics.com/#!appointment/2017-01-30T08:00:00.000Z/7441302:

```
PUT: http://dev.loconomics.com/api/v1/en-US/me/service-professional-booking/812

bookingID=812
jobTitleID=76
clientUserID=562
serviceAddress[addressID]=0
serviceAddress[addressName]
serviceAddress[jobTitleID]=0
serviceAddress[userID]=0
serviceAddress[isServiceArea]=false
serviceAddress[isServiceLocation]=false
serviceAddress[serviceRadius]=0
serviceAddress[kind]
startTime=2017-01-30T17:15:00.000Z
services[]=161
preNotesToClient=Just+at+Test.+Looks+like+they+didn't+save!
preNotesToSelf
postNotesToClient
postNotesToSelf
allowBookUnavailableTime=false
```

Here is the POST data from http://dev.loconomics.com/#!appointment/2017-01-27T18:45:00.000Z/7441471: 

```
POST: http://dev.loconomics.com/api/v1/en-US/me/service-professional-booking/813

bookingID=813
jobTitleID=76
clientUserID=562
serviceAddress[addressID]=0
serviceAddress[addressName]
serviceAddress[jobTitleID]=0
serviceAddress[userID]=0
serviceAddress[isServiceArea]=false
serviceAddress[isServiceLocation]=false
serviceAddress[serviceRadius]=0
serviceAddress[kind]
startTime=2017-01-27T18:45:00.000Z
services[]=161
preNotesToClient
preNotesToSelf
postNotesToClient=Good+conversation!
postNotesToSelf
allowBookUnavailableTime=false
```

**Comment by IagoSRL** [comment]
@situatedbit OK, that's a new error that showed up after fix the initial one, but same effect for this issue goal. I researched that, since seems familiar to something I fixed at #60, and ended being the same problem but at a different place, fixed at 'client-booking' API, and here happens at service-professional-booking API. When we introduced the change that allowed phone-only bookings, where location is not required, we only did it at client-booking creation, not update (fixed) and not at service-professional-booking. I fixed this last now for the REST API, at a new branch here and uploaded to *dev* where can be tested now (I did a test already with your booking :-). Please double check.

**Note:** this shows up yet another problem, or just different behavior with client-booking: at service-professional-booking, the non required address still show up an empty field at UI, and the step-by-step process to create one requires an address ever, without check for phone-only services (just front-end, the server did not require the address now).

**Comment by situatedbit** [comment]
@IagoSRL I was able to confirm your fixes on _dev_. I created a booking without a location, then I modified it both prior to confirming the appointment and after confirming the appointment. This is fixed.

**Comment by IagoSRL** [comment]
thanks!

**Comment by IagoSRL** [comment]
Merged this into is60-bug-dashboard-map branch, since was based on that, and closing. Will reach master when we close #60 too.
