### ISSUE TITLE
Bug S1: Error Loading Map on Dashboard

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics#60]
![screen shot 2016-11-30 at 10 47 30 am](https://cloud.githubusercontent.com/assets/1202838/20766294/b10ef6ce-b6ea-11e6-8328-5f43e81acc6d.png)

**Comment by IagoSRL** [comment]
Error says that the address is null, so I suppose the error happens when a service is 'phone only'. I'm adding a check to hide and not process the location/map link area when no address.

**Comment by IagoSRL** [comment]
Uploaded to *dev* a fix, to be confirmed

**Comment by IagoSRL** [comment]
Uploaded to *dev* updated code, with additional fixes for bugs I found when trying to confirm this is fixed.

The different bugs were all related, as this, to the fact that the serviceAddress chosen at client booking was not being saved (errors at appointment, calendar, dashboard activities, because of null reference at address); and when editing a client booking, similar errors like requiring the user to choose or create a serviceAddress even when the services didn't require it (were phone-only), behaving the rules different than when creating the booking.

**I fixed that bugs**, I was able to create a client booking, with serviceAddress being correctly saved and bookings that didn't required a booking; and about this issue, dashboard is not throwing me errors on phone-only (no address) bookings. Of course, I wait for double check by you testing this.

The commented bugs means that #119 is probably fixed, and #20 seems related (maybe part of it is fixed bug not all). Both require review testing against current *dev* --will comment there.

**Comment by IagoSRL** [comment]
Hi @joshdanielson, I think this is fixed, and related things at #119 too; the fixes at #119 are based on the commits here so merging that branch will merge this one too and I prefer to confirm this first. Not ideal situation, but both are very related; please test and let me know.

Still, at #119, that *looks* like fixed, shows we (or me?) forgot to introduce the non-address/phone-only capability that exists at client-booking into the service-professional-booking UI. Please go to #119 in case you have comments, but I think is just "to skip the select address step and hide address field".

**Comment by joshdanielson** [comment]
@IagoSRL just testing this on dev (the error still shows on live) but can't see my client dashboard (#138) to see if there's an error. 

I guess I should ask first, should I be testing on the branch or dev?

**Comment by IagoSRL** [comment]
It's on *dev*, so test there (commented in a previous comment). I will investigate #138 separately, there you commented it failed at Safari but worked on Chrome, so can you check this error on Chrome? At Safari, if still the login is broken, can you (after press login) manually change the URL to #!dashboard in order to verify this issue, with the same account you found this bug?

**Comment by joshdanielson** [comment]
@IagoSRL just trying this on Chrome as the client (543) and get this error message (booked successfully and showing up on the service professional's (540) dashboard just fine).
![screen shot 2017-02-04 at 10 23 01 am](https://cloud.githubusercontent.com/assets/1202838/22620605/1253ea04-eac4-11e6-9524-abde6b5d1cc6.png)

**Comment by IagoSRL** [comment]
Strange.. that message means 'login required with professional access to this resource', for the 'upcoming bookings' API, don't have sense since you are logged-in. Some detail at console, network?

**Comment by joshdanielson** [comment]
@IagoSRL here's the error message:
http://dev.loconomics.com/api/v1/en-US/me/upcoming-bookings?_=1485813539780 Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by IagoSRL** [comment]
Just what I though. The strange is that happens when you are logged

**Comment by joshdanielson** [comment]
@IagoSRL it appears to be working! Still weird login issues that I'll document in #138
![screen shot 2017-02-06 at 9 17 27 am](https://cloud.githubusercontent.com/assets/1202838/22657969/364f6e3a-ec4d-11e6-8044-30eba436fc5d.png)

Closing.
